stages:
  - test

.test-template: &test-template
  stage: test
  tags:
    - no-docker
  script:
    - source /etc/profile.d/ncs.sh
    - /etc/init.d/ncs start
    - ln -s $(pwd) /var/opt/ncs/packages
    - cd src && make
    - ( echo "request packages reload" | ncs_cli -g ncsadmin -u admin ) || true
    - sleep 60
    - STATUS=$(echo "show packages package oper-status" | ncs_cli -g ncsadmin -u admin)
    - echo "$STATUS"
    - echo "$STATUS" | grep "oper-status up"
  artifacts:
    paths:
      - .


test-4.2.3:
  image: repo.dev.terastrm.net:5000/ci-cisco-nso:4.2.3
  <<: *test-template

test-4.3.1:
  image: repo.dev.terastrm.net:5000/ci-cisco-nso:4.3.1
  <<: *test-template

test-4.4:
  image: repo.dev.terastrm.net:5000/ci-cisco-nso:4.4
  <<: *test-template
